---
apiVersion: v1
kind: Namespace
metadata:
  name: jumia-phone-validator
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jumia-phone-validator-deployment
  namespace: jumia-phone-validator
  labels:
    app: jumia-phone-validator
spec:
  replicas: 3
  selector:
    matchLabels:
      app: jumia-phone-validator
  template:
    metadata:
      labels:
        app: jumia-phone-validator
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/arch
                operator: In
                values:
                - amd64
                - arm64
      containers:
      - name: nginx
        image: public.ecr.aws/nginx/nginx:1.21
        ports:
        - name: http
          containerPort: 80
        imagePullPolicy: IfNotPresent
      nodeSelector:
        kubernetes.io/os: linux